---
version: "3.8"
services:
  nautobot:
    deploy:
      replicas: 2
    build:
      target: "nautobot"
    image: "ipfdemo/nautobot-ipfdemo:local"
    ports:
      - "8080"
      - "8443"
    env_file:
      - "./production.env"
      - "./creds.env"
  # rq-worker:
  #   deploy:
  #     replicas: 2
  #   image: "ipfdemo/nautobot-ipfdemo:local"
  #   env_file:
  #     - "./production.env"
  #     - "./creds.env"
  worker:
    deploy:
      replicas: 2
    image: "ipfdemo/nautobot-ipfdemo:local"
    env_file:
      - "./production.env"
      - "./creds.env"
  nginx:
    image: "nginx:1.21.3"
    depends_on:
      - "nautobot"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nautobot.key:/opt/nautobot.key:ro"
      - "./nautobot.crt:/opt/nautobot.crt:ro"
  prometheus:
    image: "prom/prometheus:v2.30.3"
    command: "--storage.tsdb.retention.time=1d --config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    env_file:
      - "./production.env"
      - "./creds.env"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    tty: true
volumes:
  prometheus_data:  # yamllint disable-line rule:empty-values
